version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: urbanpower-postgres
    restart: always
    environment:
      POSTGRES_DB: urbanpower
      POSTGRES_USER: urbanpower_user
      POSTGRES_PASSWORD: urbanpower_pass_2026
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
