"""update_booking_and_create_timeslot

Revision ID: 3684c00ff5f0
Revises: 627501f75976
Create Date: 2026-06-24 10:54:39.600688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3684c00ff5f0'
down_revision: Union[str, Sequence[str], None] = '627501f75976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeslots_id'), 'timeslots', ['id'], unique=False)
    op.create_index(op.f('ix_timeslots_service_id'), 'timeslots', ['service_id'], unique=False)
    op.add_column('bookings', sa.Column('address_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('timeslot_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='booking_status_enum', native_enum=False), nullable=False))
    op.add_column('bookings', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('notes', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_bookings_address_id'), 'bookings', ['address_id'], unique=False)
    op.create_index(op.f('ix_bookings_timeslot_id'), 'bookings', ['timeslot_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'timeslots', ['timeslot_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bookings', 'amount')
    op.drop_column('bookings', 'booking_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_timeslot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_address_id'), table_name='bookings')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'total_price')
    op.drop_column('bookings', 'status')
    op.drop_column('bookings', 'timeslot_id')
    op.drop_column('bookings', 'address_id')
    op.drop_index(op.f('ix_timeslots_service_id'), table_name='timeslots')
    op.drop_index(op.f('ix_timeslots_id'), table_name='timeslots')
    op.drop_table('timeslots')
    # ### end Alembic commands ###
