"""create_maintenance_tables

Revision ID: 627501f75976
Revises: 8ccee0840b9f
Create Date: 2026-06-23 21:21:17.997093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627501f75976'
down_revision: Union[str, Sequence[str], None] = '8ccee0840b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_categories_id'), 'maintenance_categories', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_categories_name'), 'maintenance_categories', ['name'], unique=False)
    op.create_table('maintenance_services',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['maintenance_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_services_category_id'), 'maintenance_services', ['category_id'], unique=False)
    op.create_index(op.f('ix_maintenance_services_id'), 'maintenance_services', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_services_name'), 'maintenance_services', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_services_name'), table_name='maintenance_services')
    op.drop_index(op.f('ix_maintenance_services_id'), table_name='maintenance_services')
    op.drop_index(op.f('ix_maintenance_services_category_id'), table_name='maintenance_services')
    op.drop_table('maintenance_services')
    op.drop_index(op.f('ix_maintenance_categories_name'), table_name='maintenance_categories')
    op.drop_index(op.f('ix_maintenance_categories_id'), table_name='maintenance_categories')
    op.drop_table('maintenance_categories')
    # ### end Alembic commands ###
