"""create_scrap_tables

Revision ID: 9ff0d0fe8592
Revises: 09fe3e7afd4a
Create Date: 2026-06-23 20:10:38.873090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff0d0fe8592'
down_revision: Union[str, Sequence[str], None] = '09fe3e7afd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_categories_id'), 'scrap_categories', ['id'], unique=False)
    op.create_index(op.f('ix_scrap_categories_name'), 'scrap_categories', ['name'], unique=False)
    op.create_table('scrap_items',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['scrap_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_items_category_id'), 'scrap_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_scrap_items_id'), 'scrap_items', ['id'], unique=False)
    op.create_index(op.f('ix_scrap_items_name'), 'scrap_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrap_items_name'), table_name='scrap_items')
    op.drop_index(op.f('ix_scrap_items_id'), table_name='scrap_items')
    op.drop_index(op.f('ix_scrap_items_category_id'), table_name='scrap_items')
    op.drop_table('scrap_items')
    op.drop_index(op.f('ix_scrap_categories_name'), table_name='scrap_categories')
    op.drop_index(op.f('ix_scrap_categories_id'), table_name='scrap_categories')
    op.drop_table('scrap_categories')
    # ### end Alembic commands ###
