"""add_booking_reference_and_photos

Revision ID: cc6815713133
Revises: 3684c00ff5f0
Create Date: 2026-06-24 11:45:50.604430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6815713133'
down_revision: Union[str, Sequence[str], None] = '3684c00ff5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_reference', sa.String(length=50), nullable=False))
    op.add_column('bookings', sa.Column('photos', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_bookings_booking_reference', 'bookings', ['booking_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bookings_booking_reference', 'bookings', type_='unique')
    op.drop_column('bookings', 'photos')
    op.drop_column('bookings', 'booking_reference')
    # ### end Alembic commands ###
