spring.application.name=urbanpower

spring.datasource.url=jdbc:mysql://localhost:3306/urbanpower
spring.datasource.username=root
spring.datasource.password=UrbanPower@21#Dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# JWT Config

jwt.secret=UrbanPowerSuperSecureSecretKey123456789012345
jwt.expiration=86400000
